% Script generated by Brainstorm (27-Nov-2023)

sub_list = {'PASP001','PASP002','PASP003', 'PASP004', 'PASP005', 'PASP007', 'PASP008', 'PASP013', 'PASP015', 'PASP016', 'PASP017', 'PASP022', 'PASP023', 'PASP025', 'PASP026', 'PASP027', 'PASP028', 'PASP029', 'PASP030', 'PASP031', 'PASP032','PASP018', 'PASP006'};

for sb=1: numel(sub_list)


    if  strcmp('PASP001',sub_list{sb})
        num = 548;
    elseif  strcmp('PASP002',sub_list{sb})|strcmp('PASP003',sub_list{sb})|strcmp('PASP004',sub_list{sb})|strcmp('PASP005',sub_list{sb})
        num = 553;
    elseif  strcmp('PASP007',sub_list{sb})|strcmp('PASP008',sub_list{sb})|strcmp('PASP013',sub_list{sb})|strcmp('PASP015',sub_list{sb})|strcmp('PASP016',sub_list{sb})
        num = 554;
    elseif  strcmp('PASP017',sub_list{sb})|strcmp('PASP022',sub_list{sb})|strcmp('PASP023',sub_list{sb})|strcmp('PASP025',sub_list{sb})
        num = 555;
    elseif  strcmp('PASP026',sub_list{sb})|strcmp('PASP027',sub_list{sb})|strcmp('PASP028',sub_list{sb})|strcmp('PASP029',sub_list{sb})
        num = 556;
    elseif  strcmp('PASP030',sub_list{sb})|strcmp('PASP031',sub_list{sb})|strcmp('PASP032',sub_list{sb})
        num = 557;
    else 
        num= 604;
    end

    fname = [ sub_list{sb} '/PAF_power/results_surface_' sub_list{sb} '_231128_1' num2str(num) '.mat' ];

    % Input files
    sFiles = {...
        fname};
    RawFiles = {...
        'E:\gifty_from_BS\PAF_Power'};
    
    % Start a new report
    bst_report('Start', sFiles);
    
    % Process: Export to SPM12 (surface)
    sFiles = bst_process('CallProcess', 'process_export_spmsurf', sFiles, [], ...
        'outputdir',  {RawFiles{1}, 'GIFTI'}, ...
        'filetag',    '', ...
        'timewindow', [0, 1], ...
        'isabs',      1);
    
    % Save and display report
    ReportFile = bst_report('Save', sFiles);
    bst_report('Open', ReportFile);
    % bst_report('Export', ReportFile, ExportDir);
    % bst_report('Email', ReportFile, username, to, subject, isFullReport);
    
    % Delete temporary files
    % gui_brainstorm('EmptyTempFolder');
end
