    % Script generated by Brainstorm (27-Nov-2023)
sub_list = {'PASP001','PASP002','PASP003', 'PASP004', 'PASP005', 'PASP007', 'PASP008', 'PASP013', 'PASP015', 'PASP016', 'PASP017', 'PASP022', 'PASP023', 'PASP025', 'PASP026', 'PASP027', 'PASP028', 'PASP029', 'PASP030', 'PASP031', 'PASP032','PASP018', 'PASP006'};

for sb=1: numel(sub_list)
    % Input files
    if  strcmp('PASP032',sub_list{sb})|strcmp('PASP018',sub_list{sb})|strcmp('PASP006',sub_list{sb})
        num = 15;
    end

    fname = [ sub_list{sb} '/PAF/results_surface_' sub_list{sb} '_231128_16' num '.mat' ];
    sFiles = {...
        fname};
    RawFiles = {...
        'E:\gifty_from_BS\PAF'};
    
    % Start a new report
    bst_report('Start', sFiles);
    
    % Process: Export to SPM12 (surface)
    sFiles = bst_process('CallProcess', 'process_export_spmsurf', sFiles, [], ...
        'outputdir',  {RawFiles{1}, 'GIFTI'}, ...
        'filetag',    '', ...
        'timewindow', [0, 1], ...
        'isabs',      1);
    
    % Save and display report
    ReportFile = bst_report('Save', sFiles);
    bst_report('Open', ReportFile);
    % bst_report('Export', ReportFile, ExportDir);
    % bst_report('Email', ReportFile, username, to, subject, isFullReport);
    
    % Delete temporary files
    % gui_brainstorm('EmptyTempFolder');
end